global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'video-processor'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/metrics'

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']