name: Deploy to DigitalOcean

# Deployment triggered at 2024-03-19
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: 18

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Create env file
        run: |
          touch .env
          echo "PORT=10000" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env
          echo "NODE_ENV=production" >> .env
        
      - name: Build Application
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          
          # Create SSH config file
          echo "Host *" > ~/.ssh/config
          echo "  IdentityFile ~/.ssh/deploy_key" >> ~/.ssh/config
          echo "  StrictHostKeyChecking yes" >> ~/.ssh/config
          echo "  UserKnownHostsFile ~/.ssh/known_hosts" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          # Debug: Show SSH files and permissions
          ls -la ~/.ssh/
          cat ~/.ssh/config
          
          # Test SSH connection with verbose output
          ssh -vvv nodejs@${{ secrets.DROPLET_IP }} 'echo "SSH test"'

      - name: Deploy to DigitalOcean
        run: |
          # Create directory if it doesn't exist
          ssh -i ~/.ssh/deploy_key nodejs@${{ secrets.DROPLET_IP }} 'mkdir -p /var/www/video-processor'
          
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=yes" \
            --exclude='.git*' \
            --exclude='node_modules' \
            --exclude='.env' \
            dist/ package*.json ecosystem.config.js \
            nodejs@${{ secrets.DROPLET_IP }}:/var/www/video-processor/

          ssh -i ~/.ssh/deploy_key nodejs@${{ secrets.DROPLET_IP }} << 'EOSSH'
            cd /var/www/video-processor
            npm ci --production
            pm2 reload ecosystem.config.js --update-env || pm2 start ecosystem.config.js
            sudo systemctl reload nginx
          EOSSH

      - name: Verify Deployment
        run: |
          sleep 10
          curl --fail --retry 3 --retry-delay 5 http://${{ secrets.DROPLET_IP }}:10000 || exit 1

      - name: Notify on Success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "✅ Successfully deployed video-processor to production"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "❌ Failed to deploy video-processor to production"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}