- name: Deploy to DigitalOcean
        if: success()
        run: |
          echo "Starting rsync from directory: $PWD"
          # First, ensure the target directory exists
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no nodejs@161.35.137.136 "mkdir -p /var/www/video-processor"
          
          # Sync all files including dist directory
          rsync -azv --delete \
            -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            --exclude='.git*' \
            --exclude='node_modules' \
            --exclude='src' \
            --exclude='.env' \
            ./ \
            nodejs@161.35.137.136:/var/www/video-processor/

          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no nodejs@161.35.137.136 << 'EOSSH'
            cd /var/www/video-processor
            echo "Current directory contents:"
            ls -la
            echo "Dist directory contents:"
            ls -la dist
            echo "Installing production dependencies..."
            npm ci --omit=dev
            echo "Checking PM2 status before restart..."
            pm2 list || echo "PM2 not running any processes"
            echo "Stopping any existing PM2 processes..."
            pm2 delete all || echo "No processes to delete"
            echo "Starting application with PM2..."
            PM2_HOME="/var/www/video-processor/.pm2" pm2 start ecosystem.config.js
            echo "Waiting for application to start..."
            sleep 5
            echo "PM2 status after start:"
            pm2 status
            echo "PM2 logs:"
            pm2 logs --lines 20
          EOSSH