name: Deploy to DigitalOcean

on:
 push:
   branches: [ main ]
 workflow_dispatch:

env:
 NODE_VERSION: 18

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     
     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
         node-version: ${{ env.NODE_VERSION }}
         
     - name: Debug Directory Structure
       run: |
         echo "Current working directory: $PWD"
         echo "Directory contents:"
         ls -la
         
     - name: Install Dependencies
       run: |
         echo "Current directory: $PWD"
         echo "Directory contents:"
         ls -la
         npm ci

     - name: Create env file
       run: |
         touch .env
         echo "PORT=10000" >> .env
         echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
         echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env
         echo "NODE_ENV=production" >> .env
       
     - name: Build Application
       run: |
         echo "Building application in directory: $PWD"
         npm run build
         echo "Build complete. Contents of dist:"
         ls -la dist/
         echo "Contents of dist/app.js:"
         cat dist/app.js || echo "app.js not found!"

     - name: Debug SSH Setup
       run: |
         mkdir -p ~/.ssh
         echo "Setting up SSH key..."
         echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
         chmod 600 ~/.ssh/deploy_key
         ssh-keyscan -H 161.35.137.136 >> ~/.ssh/known_hosts

     - name: Deploy to DigitalOcean
       run: |
         echo "Starting rsync from directory: $PWD"
         # First, ensure the target directory exists
         ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no nodejs@161.35.137.136 "mkdir -p /var/www/video-processor/logs"
         
         # Sync all files including dist directory
         rsync -azv --delete \
           -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
           --exclude='.git*' \
           --exclude='node_modules' \
           --exclude='src' \
           --exclude='.env' \
           ./ \
           nodejs@161.35.137.136:/var/www/video-processor/

         ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no nodejs@161.35.137.136 << 'EOSSH'
           cd /var/www/video-processor
           echo "Current directory contents:"
           ls -la
           
           echo "Setting up permissions..."
           sudo -n chown -R nodejs:nodejs /var/www/video-processor || true
           
           echo "Configuring firewall..."
           sudo -n ufw allow 10000/tcp || true
           sudo -n ufw status | grep 10000 || true
           
           echo "Installing PM2..."
           npm install pm2@latest || npm install pm2 --save
           PATH="$PATH:./node_modules/.bin"
           
           echo "Installing production dependencies..."
           # Remove the postinstall script before installing
           sed -i 's/"postinstall": "npm run build"//' package.json
           npm ci --omit=dev
           
           echo "Setting up directories..."
           mkdir -p logs
           chmod 777 logs
           mkdir -p .pm2
           chmod 777 .pm2
           
           echo "Starting application with PM2..."
           export PM2_HOME="/var/www/video-processor/.pm2"
           
           echo "PM2 logs directory:"
           ls -la .pm2 || true
           
           echo "Application files:"
           ls -la dist || true
           
           ./node_modules/.bin/pm2 delete all || true
           
           echo "Starting with increased logging..."
           export DEBUG=express:*,app:*
           export NODE_DEBUG=*
           ./node_modules/.bin/pm2 start ecosystem.config.js --no-daemon --no-autorestart | tee startup.log
           
           echo "Application startup log:"
           cat startup.log || true
           
           echo "Process status:"
           ps aux | grep node
           
           echo "PM2 status:"
           ./node_modules/.bin/pm2 status
           
           echo "Checking netstat for port 10000:"
           netstat -tulpn | grep 10000 || true
           
           echo "Looking for error logs..."
           find . -name "*.log" -type f -exec tail -n 50 {} \;
         EOSSH

     - name: Verify Deployment
       run: |
         echo "Waiting for application to start..."
         sleep 30
         for i in {1..5}; do
           echo "Attempt $i of 5..."
           if curl -v --fail --max-time 30 http://161.35.137.136:10000; then
             echo "Application is responding!"
             exit 0
           fi
           echo "Waiting before next attempt..."
           sleep 10
         done
         echo "Application failed to respond after 5 attempts"
         exit 1

     - name: Notify on Success
       if: success()
       uses: slackapi/slack-github-action@v1.24.0
       with:
         channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
         slack-message: "✅ Successfully deployed video-processor to production"
       env:
         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

     - name: Notify on Failure
       if: failure()
       uses: slackapi/slack-github-action@v1.24.0
       with:
         channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
         slack-message: "❌ Failed to deploy video-processor to production"
       env:
         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 